---
version: "3"

services:
    flask-app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: hieucannguyen/iss_tracker_app:1.0
        container_name: iss_tracker_app
        ports:
            - "5000:5000"

